\set db  'go1f_db'
\set usr 'go1f'

DROP DATABASE IF EXISTS :db;
DROP ROLE     IF EXISTS :usr;
DROP SCHEMA   IF EXISTS :usr;

-- set password later
CREATE USER :usr WITH PASSWORD NULL;
CREATE DATABASE :db OWNER :usr;
\c :db
CREATE SCHEMA :usr AUTHORIZATION :usr;
CREATE EXTENSION citext WITH SCHEMA :usr;

ALTER DATABASE :db SET search_path TO :usr;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
